PROGRAMS = [
    {
        "id": 1,
        "name": "4Planning",
        "platform": "yeswehack",
        "type": "web",
        "payout_min": 50,
        "payout_max": 1500,
        "currency": "EUR",
        "geo_access": "vpn",
        "geo_note": "VPN India",
        "difficulty": 2,
        "stack_tags": ["PHP", "MySQL", "Web"],
        "updated_at": "2026-06-08",
    },
    {
        "id": 2,
        "name": "Pine Labs",
        "platform": "yeswehack",
        "type": "api",
        "payout_min": 100,
        "payout_max": 3000,
        "currency": "USD",
        "geo_access": "vpn",
        "geo_note": "VPN India",
        "difficulty": 3,
        "stack_tags": ["Java", "API", "AWS"],
        "updated_at": "2026-06-05",
    },
    {
        "id": 3,
        "name": "Gojek",
        "platform": "yeswehack",
        "type": "mobile",
        "payout_min": 150,
        "payout_max": 5000,
        "currency": "USD",
        "geo_access": "vpn",
        "geo_note": "VPN Indonesia",
        "difficulty": 4,
        "stack_tags": ["Android", "Kotlin", "API"],
        "updated_at": "2026-06-02",
    },
    {
        "id": 4,
        "name": "Uber",
        "platform": "hackerone",
        "type": "web",
        "payout_min": 500,
        "payout_max": 25000,
        "currency": "USD",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 5,
        "stack_tags": ["Node.js", "Java", "API"],
        "updated_at": "2026-06-10",
    },
    {
        "id": 5,
        "name": "GitLab",
        "platform": "hackerone",
        "type": "web",
        "payout_min": 200,
        "payout_max": 10000,
        "currency": "USD",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 4,
        "stack_tags": ["Ruby", "Go", "PostgreSQL"],
        "updated_at": "2026-06-09",
    },
    {
        "id": 6,
        "name": "Shopify",
        "platform": "hackerone",
        "type": "web",
        "payout_min": 500,
        "payout_max": 50000,
        "currency": "USD",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 5,
        "stack_tags": ["Ruby on Rails", "GraphQL", "API"],
        "updated_at": "2026-06-11",
    },
    {
        "id": 7,
        "name": "NATO",
        "platform": "intigriti",
        "type": "web",
        "payout_min": 100,
        "payout_max": 4000,
        "currency": "EUR",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 4,
        "stack_tags": [".NET", "Active Directory", "Web"],
        "updated_at": "2026-06-01",
    },
    {
        "id": 8,
        "name": "Bmw",
        "platform": "intigriti",
        "type": "mobile",
        "payout_min": 100,
        "payout_max": 6000,
        "currency": "EUR",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 3,
        "stack_tags": ["iOS", "Android", "API"],
        "updated_at": "2026-05-30",
    },
    {
        "id": 9,
        "name": "Wise",
        "platform": "bugcrowd",
        "type": "api",
        "payout_min": 150,
        "payout_max": 8000,
        "currency": "USD",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 4,
        "stack_tags": ["Java", "Kotlin", "API"],
        "updated_at": "2026-06-07",
    },
    {
        "id": 10,
        "name": "Mercado Libre",
        "platform": "hackerone",
        "type": "web",
        "payout_min": 100,
        "payout_max": 7000,
        "currency": "USD",
        "geo_access": "blocked",
        "geo_note": "Blocked in Italy",
        "difficulty": 3,
        "stack_tags": ["PHP", "Java", "API"],
        "updated_at": "2026-05-28",
    },
    {
        "id": 11,
        "name": "Coinbase",
        "platform": "hackerone",
        "type": "web",
        "payout_min": 200,
        "payout_max": 50000,
        "currency": "USD",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 5,
        "stack_tags": ["Go", "TypeScript", "API"],
        "updated_at": "2026-06-10",
    },
    {
        "id": 12,
        "name": "Dropbox",
        "platform": "hackerone",
        "type": "web",
        "payout_min": 200,
        "payout_max": 15000,
        "currency": "USD",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 4,
        "stack_tags": ["Python", "Go", "API"],
        "updated_at": "2026-06-04",
    },
    {
        "id": 13,
        "name": "Revolut",
        "platform": "intigriti",
        "type": "mobile",
        "payout_min": 100,
        "payout_max": 12000,
        "currency": "EUR",
        "geo_access": "ok",
        "geo_note": "OK from Italy",
        "difficulty": 4,
        "stack_tags": ["Kotlin", "Swift", "API"],
        "updated_at": "2026-06-03",
    },
    {
        "id": 14,
        "name": "Sony",
        "platform": "bugcrowd",
        "type": "web",
        "payout_min": 100,
        "payout_max": 5000,
        "currency": "USD",
        "geo_access": "vpn",
        "geo_note": "VPN USA",
        "difficulty": 2,
        "stack_tags": ["Java", "Web", "AWS"],
        "updated_at": "2026-05-25",
    },
    {
        "id": 15,
        "name": "Snapchat",
        "platform": "yeswehack",
        "type": "mobile",
        "payout_min": 200,
        "payout_max": 20000,
        "currency": "USD",
        "geo_access": "blocked",
        "geo_note": "Blocked in Italy",
        "difficulty": 5,
        "stack_tags": ["Android", "iOS", "API"],
        "updated_at": "2026-05-20",
    },
]
